### ISSUE TITLE
can't execute `catsay` command on arch linux

### ISSUE THREAD

**Issue by fauzipadlaw** [muhammadmuzzammil1998/catsay#13]
**Describe the bug**
can't execute `catsay` command on arch linux

**To Reproduce**
1. Open terminal
2. type catsay
3. bash: catsay: command not found

**Screenshots**

![image](https://user-images.githubusercontent.com/15975922/47384960-f1363b80-d732-11e8-8874-fcbe44be2dad.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64

**Comment by fauzipadlaw** [comment]
solved, i downloaded the binary. close this issue

**Comment by muhammadmuzzammil1998** [comment]
Yeah, I see that you were trying to install catsay using snap. My bad, I was testing distribution methods and forgot to remove the project from snapcraft. I couldn't get it to work from snap too so I dropped the idea. Will try to remove the project from snapcraft to avoid further confusion.

Thanks! :)

**Comment by muhammadmuzzammil1998** [comment]
Glad you liked it 🙂
