### ISSUE TITLE
Cat looks like a bunny

### ISSUE THREAD

**Issue by muhammadmuzzammil1998** [muhammadmuzzammil1998/catsay#3]
```
 _________________
/ I am a cat and  \
\ I meow          /
 -----------------
  (\__/)||
  (•ㅅ•)||
  /    \っ
```

But still, will redesign the cat to have one more hand and a tail. :)

Open to ideas! 🐱 🐰

**Comment by muhammadmuzzammil1998** [comment]
```
 _________________
< Testing cat 123 >
 -----------------
  (\__/)||
_ (•ㅅ•)||
 \/o   \っ
```

**Comment by chillidoor** [comment]
It looks like there are already some established ASCII cat emojis (of course there would be, haha). https://cutekaomoji.com/animals/cats/

I think that using something similar to one of those would stop any bunny/cat confusion.

Perhaps something like this?
```
-------------------
| Kitty says meow |
-------------------
   /\     /\   ||
 (=＾• ⋏ •＾=)っ||
```

**Comment by muhammadmuzzammil1998** [comment]
Of course, there would exist such a thing 😂 So much potential!
But sadly, most of them aren't supported in the terminal 😞 so it would have to also work on just the ASCII characters.

The one you gave would look like this in ASCII only:
```
-------------------
| Kitty says meow |
-------------------
  /\_____/\  ||
 (=^* > *^=)>||
```
ASCII only of https://github.com/muhammadmuzzammil1998/catsay/issues/3#issuecomment-418027948
```
 _________________________
< I am in ascii only mode >
 -------------------------
   (\__/) ||
_  (*/\*) ||
  \/o   \ >
```

**Comment by muhammadmuzzammil1998** [comment]
But this gives me an idea of having custom cats which users can set. 🎉
